version: '3'

services:
  webserver:
    image: nginx
    ports:
      - "83:80"
    volumes:
      - ./web:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf/
    depends_on:
      - php
  php:
    image: php:8.2.11-fpm
    volumes:
      - ./web/:/var/www/html
